# Default configuration as dict (for backward compatibility)
DEFAULT_CONFIG = {
    "system": {
        "user_id": None,  # Will be set during initialization
        "user_name": "You",
        "char_name": "Character Name",
        "language": "en-US",
        "system_prompt": "",
        "theme": "default",
    },
    "core": {
        "version": "1.0.0",
        "env": "dev",
        "debug": False,
    },
    "voice": {
        "enabled": True,
        "output_id": 0,
        "windows_output_id": 0,
        "language": "en-US",
        "use_rvc": False,
        "use_windows_output": False,
        "streaming_tts": False,
        "enable_fallback": True,
        "active_module": "edge",
        "voice_modules": {
            "elevenlabs": {
                "api_key": "",
                "voice_id": "",
                "model_id": "",
                "stability": 0.5,
                "similarity": 0.75,
            },
            "edge": {"voice_language": "en-US-JennyNeural"},
        },
        "voice_language": "en-US-JennyNeural",
    },
    "stt": {"language": "en-US", "auto_detect": False},
    "modules": {
        "vtube_studio": False,
        "whisper": True,
        "minecraft": False,
        "gaming": False,
        "alarm": False,
        "discord": False,
        "rag": True,
        "visual": True,
    },
    "audio": {
        "input_device_id": 0,
        "sample_rate": 16000,
        "channels": 1,
        "chunk_size": 1024,
        "enable_vad": True,
        "vad_threshold": 0.5,
        "silence_timeout": 3.0,
        "min_audio_length": 0.5,
        "max_audio_length": 120.0,
        "trigger_words": [],
        "ignore_trigger_words": True,
    },
    "vision": {
        "enabled": True,
        "active_provider": "apple_vision",
        "monitor_index": 0,
        "fps": 5,
        "buffer_sec": 4,
        "downscale_width": 1280,
        "yolo_enabled": False,
        "ocr_lang": "eng",
        "ocr_min_conf": 70,
        "ocr_max_lines": 5,
        "region": None,
        "capture_mode": "monitor",
        "window_title": "",
        "window_process": "",
        "debug_save": False,
        "debug_path": "./temp/vision",
        "vision_modules": {
            "apple_vision": {"model_id": "apple/FastVLM-1.5B", "max_tokens": 128},
            "llava": {"model_id": "llava-hf/llava-1.5-7b-hf", "max_tokens": 128},
        },
    },
    "rag": {
        "enabled": True,
        "embeddingModel": "all-MiniLM-L6-v2",
        "vectorDbPath": "./data/vector_db",
        "chunkSize": 500,
        "chunkOverlap": 50,
        "topK": 5,
        "similarityThreshold": 0.7,
        "enableCaching": True,
        "cacheTtl": 60,
        "searchStrategy": {
            "sessionContext": {
                "enabled": True,
                "maxMessages": 32,
                "lookBackToToday": True,
            },
            "dailySummary": {"enabled": True, "lookBackDays": 7, "useTags": True},
            "longTermMemory": {
                "enabled": True,
                "vectorSearch": True,
                "graphSearch": True,
                "priorityRules": True,
            },
            "fallback": {"askUser": True, "autoLearn": True},
        },
        "memory": {
            "facts": {
                "enabled": True,
                "priorityRules": ["user", "name", "person"],
                "autoUpdate": True,
            },
            "graph": {"enabled": True, "relationships": True, "inference": True},
        },
        "retrieval": {
            "recent": {"limit": 32},
            "session": {
                "enabled": True,
                "window": "day",
            },
            "keyword": {
                "enabled": True,
                "max_candidates": 8,
                "min_score": 0.2,
                "min_overlap": 0.25,
                "boost_user": 1.05,
                "boost_assistant": 0.95,
                "stopwords": [
                    "это",
                    "как",
                    "или",
                    "если",
                    "when",
                    "then",
                    "with",
                    "что",
                    "and",
                    "the",
                ],
            },
            "vectors": {
                "primary": "embed768",
                "profiles": {
                    "embed768": {
                        "label": "768d • nomic-embed-text",
                        "enabled": True,
                        "provider": "ollama",
                        "model": "nomic-embed-text",
                        "endpoint": "http://localhost:11434/api/embeddings",
                        "timeout": 30,
                    "max_retries": 2,
                    "retry_backoff": 0.75,
                    "top_k": 8,
                    "threshold": 0.9,
                },
                "embed384": {
                    "label": "384d • all-MiniLM-L6-v2",
                    "enabled": True,
                    "provider": "st",
                    "model": "all-MiniLM-L6-v2",
                    "device": "cpu",
                    "top_k": 10,
                    "threshold": 0.9,
                },
            },
        },
        "short_term": {
            "enabled": True,
            "threshold": 0.75,
            },
            "rerank": {
                "enabled": True,
                "top_n": 6,
                "use_primary_rerank": True,
                "boost_recency": 0.15,
                "weights": {
                    "embedding": 0.65,
                    "keyword": 0.25,
                    "short_term": 0.1,
                },
            },
        },
        "lore": {
            "top_k": 3,
            "similarity_threshold": 0.7,
        },
    },
    "analyzer": {
        "active_provider": "openrouter",
        "fallback_order": ["ollama"],
        "providers": {
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.7,
                "max_tokens": 1024,
            },
            "ollama": {"model": "llama3.2", "temperature": 0.7, "max_tokens": 1024},
        },
    },
    "moral": {
        "enabled": True,
        "active_provider": "ollama",
        "fallback_order": ["openrouter", "heuristic"],
        "providers": {
            "heuristic": {},
            "ollama": {"model": "llama3.2", "temperature": 0.6, "max_tokens": 512},
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.6,
                "max_tokens": 512,
            },
        },
    },
    "memory": {
        "recent_limit": 32,
        "similarity_threshold": 0.7,
        "session_window": "day",
        "session_enabled": True,
        "embedding_provider": "auto",
        "embedding_model": "nomic-embed-text",
    },
    "api": {
        "type": "Ollama",
        "streaming": True,
        "model": "llama3.2",
        "visual_model": "apple/FastVLM-1.5B",
        "token_limit": 4096,
        "message_pair_limit": 10,
        "active_provider": "ollama",
        "fallback_order": ["openrouter"],
        "providers": {
            "ollama": {
                "model": "llama3.2",
                "temperature": 0.85,
                "max_tokens": 2048,
                "streaming": True,
            },
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.85,
                "max_tokens": 2048,
                "base_url": "https://openrouter.ai/api/v1",
            },
        },
    },
    "generate_settings": {
        "temperature": 0.85,
        "min_p": 0.05,
        "top_p": 0.9,
        "top_k": 50,
        "repeat_penalty": 1.2,
        "stop": None,
        "num_predict": 2048,
        "name": "Default",
        "description": "Basic generation parameters",
    },
}
