# Default configuration as dict (for backward compatibility)
DEFAULT_CONFIG = {
    "user_id": None,  # Will be set during initialization
    "char_name": "Character Name",
    "user_name": "You",
    "language": "en-US",
    "system": {
        "user_id": None,
        "user_name": "You",
        "char_name": "Character Name",
        "system_prompt": "",
        "theme": "default",
    },
    "core": {
        "version": "1.0.0",
        "env": "dev",
        "debug": False,
    },
    "voice": {
        "enabled": True,
        "output_id": 0,
        "windows_output_id": 0,
        "language": "en-US",
        "use_rvc": False,
        "use_windows_output": False,
        "streaming_tts": False,
        "enable_fallback": True,
        "active_module": "edge",
        "voice_modules": {
            "elevenlabs": {
                "api_key": "",
                "voice_id": "",
                "model_id": "",
                "stability": 0.5,
                "similarity": 0.75,
            },
            "edge": {"voice_language": "en-US-JennyNeural"},
        },
        "voice_language": "en-US-JennyNeural",
    },
    "stt": {"language": "en-US", "auto_detect": False},
    "modules": {
        "vtube_studio": False,
        "whisper": True,
        "minecraft": False,
        "gaming": False,
        "alarm": False,
        "discord": False,
        "rag": True,
        "visual": True,
    },
    "audio": {
        "input_device_id": 0,
        "sample_rate": 16000,
        "channels": 1,
        "chunk_size": 1024,
        "enable_vad": True,
        "vad_threshold": 0.5,
        "silence_timeout": 3.0,
        "min_audio_length": 0.5,
        "max_audio_length": 120.0,
        "trigger_words": [],
        "ignore_trigger_words": True,
    },
    "vision": {
        "enabled": True,
        "active_provider": "apple_vision",
        "monitor_index": 0,
        "fps": 5,
        "buffer_sec": 4,
        "downscale_width": 1280,
        "yolo_enabled": False,
        "ocr_lang": "eng",
        "ocr_min_conf": 70,
        "ocr_max_lines": 5,
        "region": None,
        "capture_mode": "monitor",
        "window_title": "",
        "window_process": "",
        "debug_save": False,
        "debug_path": "./temp/vision",
        "vision_modules": {
            "apple_vision": {"model_id": "apple/FastVLM-1.5B", "max_tokens": 128},
            "llava": {"model_id": "llava-hf/llava-1.5-7b-hf", "max_tokens": 128},
        },
    },
    "rag": {
        "enabled": True,
        "embeddingModel": "all-MiniLM-L6-v2",
        "vectorDbPath": "./data/vector_db",
        "chunkSize": 500,
        "chunkOverlap": 50,
        "topK": 5,
        "similarityThreshold": 0.7,
        "enableCaching": True,
        "cacheTtl": 60,
        "searchStrategy": {
            "sessionContext": {
                "enabled": True,
                "maxMessages": 32,
                "lookBackToToday": True,
            },
            "dailySummary": {"enabled": True, "lookBackDays": 7, "useTags": True},
            "longTermMemory": {
                "enabled": True,
                "vectorSearch": True,
                "graphSearch": True,
                "priorityRules": True,
            },
            "fallback": {"askUser": True, "autoLearn": True},
        },
        "memory": {
            "facts": {
                "enabled": True,
                "priorityRules": ["user", "name", "person"],
                "autoUpdate": True,
            },
            "graph": {"enabled": True, "relationships": True, "inference": True},
        },
    },
    "analyzer": {
        "active_provider": "openrouter",
        "fallback_order": ["ollama"],
        "providers": {
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.7,
                "max_tokens": 1024,
            },
            "ollama": {"model": "llama3.2", "temperature": 0.7, "max_tokens": 1024},
        },
    },
    "memory": {
        "recent_limit": 32,
        "similarity_threshold": 0.7,
        "session_window": "day",
        "session_enabled": True,
        "embedding_provider": "auto",
        "embedding_model": "nomic-embed-text",
    },
    "api": {
        "type": "Ollama",
        "streaming": True,
        "model": "llama3.2",
        "visual_model": "apple/FastVLM-1.5B",
        "token_limit": 4096,
        "message_pair_limit": 10,
        "active_provider": "ollama",
        "fallback_order": ["openrouter"],
        "providers": {
            "ollama": {
                "model": "llama3.2",
                "temperature": 0.85,
                "max_tokens": 2048,
                "streaming": True,
            },
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.85,
                "max_tokens": 2048,
                "base_url": "https://openrouter.ai/api/v1",
            },
        },
    },
    "generate_settings": {
        "temperature": 0.85,
        "min_p": 0.05,
        "top_p": 0.9,
        "top_k": 50,
        "repeat_penalty": 1.2,
        "stop": None,
        "num_predict": 2048,
        "name": "Default",
        "description": "Basic generation parameters",
    },
}
